server:
 port: 8888 

spring:
 profiles:
  active: native
 cloud:
  config:
   server:
    native: 
     searchLocations: file:///C:/Users/Rafik.Bouchemma/eclipse-workspace/configurationserver/src/main/resources/config/licensingservice/